debug: true
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  thymeleaf:
    spring:
      thymeleaf:
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
        cache: false

